// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Apply(arg1) {
  return window['go']['main']['App']['Apply'](arg1);
}

export function Categories() {
  return window['go']['main']['App']['Categories']();
}

export function ClearCoverOverride(arg1) {
  return window['go']['main']['App']['ClearCoverOverride'](arg1);
}

export function ConfigStatus() {
  return window['go']['main']['App']['ConfigStatus']();
}

export function ConfirmApply(arg1, arg2) {
  return window['go']['main']['App']['ConfirmApply'](arg1, arg2);
}

export function ConfirmResetCoverCache() {
  return window['go']['main']['App']['ConfirmResetCoverCache']();
}

export function ConfirmUndo(arg1) {
  return window['go']['main']['App']['ConfirmUndo'](arg1);
}

export function ListCategoryWarnings() {
  return window['go']['main']['App']['ListCategoryWarnings']();
}

export function ListLibrary(arg1) {
  return window['go']['main']['App']['ListLibrary'](arg1);
}

export function ListOperationBatches() {
  return window['go']['main']['App']['ListOperationBatches']();
}

export function ListPDFCoverCandidates(arg1) {
  return window['go']['main']['App']['ListPDFCoverCandidates'](arg1);
}

export function OpenFile(arg1) {
  return window['go']['main']['App']['OpenFile'](arg1);
}

export function PickCoverImageFile() {
  return window['go']['main']['App']['PickCoverImageFile']();
}

export function Recompute(arg1) {
  return window['go']['main']['App']['Recompute'](arg1);
}

export function ResetCoverCache() {
  return window['go']['main']['App']['ResetCoverCache']();
}

export function Scan() {
  return window['go']['main']['App']['Scan']();
}

export function SetCoverOverride(arg1, arg2) {
  return window['go']['main']['App']['SetCoverOverride'](arg1, arg2);
}

export function SetCoverOverrideCustomFromFile(arg1, arg2) {
  return window['go']['main']['App']['SetCoverOverrideCustomFromFile'](arg1, arg2);
}

export function UndoBatch(arg1) {
  return window['go']['main']['App']['UndoBatch'](arg1);
}
