// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {appapi} from '../models';

export function Apply(arg1:Array<appapi.BookView>):Promise<appapi.ApplyResult>;

export function Categories():Promise<Array<appapi.DestinationView>>;

export function ClearCoverOverride(arg1:string):Promise<string>;

export function ConfigStatus():Promise<appapi.ConfigStatusView>;

export function ConfirmApply(arg1:number,arg2:string):Promise<boolean>;

export function ConfirmResetCoverCache():Promise<boolean>;

export function ConfirmUndo(arg1:number):Promise<boolean>;

export function GetScanConcurrency():Promise<appapi.ScanConcurrencyView>;

export function ListCategoryWarnings():Promise<Array<appapi.CategoryWarningView>>;

export function ListLibrary(arg1:boolean):Promise<appapi.LibraryView>;

export function ListOperationBatches():Promise<Array<appapi.OperationBatchView>>;

export function ListPDFCoverCandidates(arg1:string):Promise<Array<appapi.CoverCandidateView>>;

export function OpenFile(arg1:string):Promise<void>;

export function PickCoverImageFile():Promise<string>;

export function Recompute(arg1:appapi.BookView):Promise<appapi.BookView>;

export function ResetCoverCache():Promise<void>;

export function Scan():Promise<Array<appapi.BookView>>;

export function SetCoverOverride(arg1:string,arg2:number):Promise<string>;

export function SetCoverOverrideCustomFromFile(arg1:string,arg2:string):Promise<string>;

export function SetScanConcurrency(arg1:number):Promise<void>;

export function UndoBatch(arg1:string):Promise<void>;
