// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Apply(arg1) {
  return window['go']['main']['App']['Apply'](arg1);
}

export function ConfigStatus() {
  return window['go']['main']['App']['ConfigStatus']();
}

export function ConfirmApply(arg1, arg2) {
  return window['go']['main']['App']['ConfirmApply'](arg1, arg2);
}

export function ListCategoryWarnings() {
  return window['go']['main']['App']['ListCategoryWarnings']();
}

export function ListOperationBatches() {
  return window['go']['main']['App']['ListOperationBatches']();
}

export function Recompute(arg1) {
  return window['go']['main']['App']['Recompute'](arg1);
}

export function Scan() {
  return window['go']['main']['App']['Scan']();
}
