// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {appapi} from '../models';

export function Apply(arg1:Array<appapi.BookView>):Promise<appapi.ApplyResult>;

export function ConfigStatus():Promise<appapi.ConfigStatusView>;

export function ConfirmApply(arg1:number,arg2:string):Promise<boolean>;

export function Recompute(arg1:appapi.BookView):Promise<appapi.BookView>;

export function Scan():Promise<Array<appapi.BookView>>;
